### ISSUE TITLE
slack service crash

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#119]
This morning at 03:58 PDT, the slack service crashed.  This is definitely the worst of our services to have to down, because we rely on it to get out error messages from everyone else.

Slight problem: I don't know why it crashed.
- At 03:57:00, slack received a ping from the pinger service
- At 03:57:02, slack received the alert that `channel_b_psyllid` still wasn't working (this never gets sent out)
- At 03:58:45, slack crashes with the below error and traceback

So somehow slack fails to process a routine alert that it's done right 1000 times?  I checked every other machine, no other crashed services or entries in stderr logfiles which slack could have picked up and choked on.

```
-----------------------------
2017-10-01T03:57:02[INFO    ] dripline.core.service(317) -> received a message
2017-10-01T03:57:02[DEBUG   ] dripline.core.service(358) -> Acknowledging message 7295
2017-10-01T03:57:02[DEBUG   ] dripline.core.message(154) -> original msg was: {"timestamp": "2017-10-01T10:57:02Z", "msgtype": 4, "payload": "The following services are not responding:\nchannel_b_psyllid\n", "sender_info": {"username": "project8", "exe": "/home/project8/python_environments/latest_version/bin/dragonfly", "package": "dripline", "service_name": "", "hostname": "myrna", "version": "wp2.1.1", "commit": "g954a659"}}
2017-10-01T03:57:02[DEBUG   ] dripline.core.message(135) -> from_dict is: {u'timestamp': u'2017-10-01T10:57:02Z', u'msgtype': 4, u'payload': u'The following services are not responding:\nchannel_b_psyllid\n', u'sender_info': {u'username': u'project8', u'exe': u'/home/project8/python_environments/latest_version/bin/dragonfly', u'package': u'dripline', u'service_name': u'', u'hostname': u'myrna', u'version': u'wp2.1.1', u'commit': u'g954a659'}}
2017-10-01T03:57:02[DEBUG   ] dripline.core.message(143) -> msgtype is 4
2017-10-01T03:57:02[DEBUG   ] dragonfly.implementations.slack_interface(81) -> parsing routing key
2017-10-01T03:57:02[DEBUG   ] dripline.core.message(154) -> original msg was: {"timestamp": "2017-10-01T10:57:02Z", "msgtype": 4, "payload": "The following services are not responding:\nchannel_b_psyllid\n", "sender_info": {"username": "project8", "exe": "/home/project8/python_environments/latest_version/bin/dragonfly", "package": "dripline", "service_name": "", "hostname": "myrna", "version": "wp2.1.1", "commit": "g954a659"}}
2017-10-01T03:57:02[DEBUG   ] dripline.core.message(135) -> from_dict is: {u'timestamp': u'2017-10-01T10:57:02Z', u'msgtype': 4, u'payload': u'The following services are not responding:\nchannel_b_psyllid\n', u'sender_info': {u'username': u'project8', u'exe': u'/home/project8/python_environments/latest_version/bin/dragonfly', u'package': u'dripline', u'service_name': u'', u'hostname': u'myrna', u'version': u'wp2.1.1', u'commit': u'g954a659'}}
2017-10-01T03:57:02[DEBUG   ] dripline.core.message(143) -> msgtype is 4
2017-10-01T03:57:02[DEBUG   ] dragonfly.implementations.slack_interface(123) -> updating history
2017-10-01T03:57:02[DEBUG   ] dragonfly.implementations.slack_interface(93) -> posting message: The following services are not responding:
channel_b_psyllid

2017-10-01T03:58:45[CRITICAL] dripline.core.service(430) -> Service <slack_interface> crashing with error message:
No JSON object could be decoded
2017-10-01T03:58:45[ERROR   ] dripline.core.service(431) -> Traceback (most recent call last):
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/dripline/core/service.py", line 428, in run
    self._connection.ioloop.start()
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 138, in start
    self.poller.start()
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 433, in start
    self.poll()
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 494, in poll
    self._handler(fileno, event, write_only=write_only)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 322, in _handle_events
    self._handle_read()
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/connection.py", line 1285, in _on_data_available
    self._process_frame(frame_value)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/connection.py", line 1365, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/connection.py", line 976, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/channel.py", line 792, in _handle_content_frame
    self._on_deliver(*response)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/pika/channel.py", line 886, in _on_deliver
    body)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/dripline/core/service.py", line 326, in on_message
    msg_type_handlers[message.msgtype](unused_channel, basic_deliver, properties, body)
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/dragonfly/implementations/slack_interface.py", line 100, in on_alert_message
    as_user='false', #false allows to send messages with unregistred username (like toto) in the channel
  File "/home/project8/python_environments/drag_v1.8.11_drip_wp2.1.1_python3.5.6_hard_v1.10.0/local/lib/python2.7/site-packages/slackclient/client.py", line 83, in api_call
    result = json.loads(self.server.api_call(method, timeout=timeout, **kwargs))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by laroque** [comment]
Some questions:

1. Did supervisor restart the service? If not, shouldn't it have? If it did, how did you discover the problem?
2. Nothing catches this exception because it isn't a `DriplineException`, it is a core python `ValueError`. The timestamps make it seem like the decoded object we see in the first few lines you paste is the prior message, not the one that triggered the crash (about which it seems we have no information). It would be useful to reproduce this. A quick look in python, this seems to come from son.loads('') (note that this is an empty string, not `None` which produces a `TypeError`). Do we potentially need another try/except block, or a check?

**Comment by wcpettus** [comment]
1. Supervisor did not restart the service, I was checking service statuses before messing with things, and discovered that the service was exited.  The supervisord.log shows:
```
2017-09-13 07:55:28,855 INFO success: slack entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2017-10-01 03:58:45,211 INFO exited: slack (exit status 0; expected)
2017-10-01 14:42:31,113 INFO spawned: 'slack' with pid 16005
```
2. The flaw is in the Slack API code, the server api_call formats the response into a string, which the client api_call decodes with json.  Something went wrong server side and it hung for ~100 s, then returned an empty string, which crashed the client api_call.
   - a try/except block will be a quick fix for this
   - should make a bug report to Slack API

**Comment by wcpettus** [comment]
As of dragonfly v1.9.1 and hardware v1.11.1, we should have:
- dragonfly code which will catch the exception
- supervisor settings which will auto-restart slack if it crashes anyway

That is a moderately satisfactory resolution to this issue (without knowing why the API had issues).
