### ISSUE TITLE
Any crashing service crashes the slow_control service

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#77]
While stress-testing the new snapshot methods, I crashed the RSA DAQ (that was expected), but it also brought down the slow control service with it.

```
2016-11-25T13:16:36[INFO    ] dripline.core.service(316) -> received a message
2016-11-25T13:16:36[DEBUG   ] dripline.core.service(363) -> Acknowledging message 436037
2016-11-25T13:16:36[DEBUG   ] dripline.core.message(166) -> original msg was: {"timestamp": "2016-11-25T21:16:36Z", "msgtype": 4, "payload": "Service <rsa_daq> crashing with error message:\nrequest response timed out", "sender_info": {"username": "pettus", "exe": "/home/pettus/python_environments/develop_sandbox/bin/dragonfly", "package": "dripline", "service_name": "", "hostname": "claude", "version": "wp2.0.0", "commit": "ge7aa091"}}
2016-11-25T13:16:36[DEBUG   ] dripline.core.message(139) -> from_dict is: {u'timestamp': u'2016-11-25T21:16:36Z', u'msgtype': 4, u'payload': u'Service <rsa_daq> crashing with error message:\nrequest response timed out', u'sender_info': {u'username': u'pettus', u'exe': u'/home/pettus/python_environments/develop_sandbox/bin/dragonfly', u'package': u'dripline', u'service_name': u'', u'hostname': u'claude', u'version': u'wp2.0.0', u'commit': u'ge7aa091'}}
2016-11-25T13:16:36[DEBUG   ] dripline.core.message(148) -> msgtype is 4
2016-11-25T13:16:36[DEBUG   ] dripline.core.gogol(48) -> in process_message callback
2016-11-25T13:16:36[DEBUG   ] dripline.core.message(166) -> original msg was: {"timestamp": "2016-11-25T21:16:36Z", "msgtype": 4, "payload": "Service <rsa_daq> crashing with error message:\nrequest response timed out", "sender_info": {"username": "pettus", "exe": "/home/pettus/python_environments/develop_sandbox/bin/dragonfly", "package": "dripline", "service_name": "", "hostname": "claude", "version": "wp2.0.0", "commit": "ge7aa091"}}
2016-11-25T13:16:36[DEBUG   ] dripline.core.message(139) -> from_dict is: {u'timestamp': u'2016-11-25T21:16:36Z', u'msgtype': 4, u'payload': u'Service <rsa_daq> crashing with error message:\nrequest response timed out', u'sender_info': {u'username': u'pettus', u'exe': u'/home/pettus/python_environments/develop_sandbox/bin/dragonfly', u'package': u'dripline', u'service_name': u'', u'hostname': u'claude', u'version': u'wp2.0.0', u'commit': u'ge7aa091'}}
2016-11-25T13:16:36[DEBUG   ] dripline.core.message(148) -> msgtype is 4
2016-11-25T13:16:36[WARNING ] dripline.core.gogol(55) -> got an exception:
'NoneType' object has no attribute 'groupdict'
2016-11-25T13:16:36[DEBUG   ] dripline.core.gogol(56) -> traceback follows:
Traceback (most recent call last):
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/dripline-wp2.0.0_python3.3.3_0_gbbf8cec-py2.7.egg/dripline/core/gogol.py", line 51, in on_alert_message
    self.this_consume(message_unpacked, method)
  File "build/bdist.linux-x86_64/egg/dragonfly/implementations/sensor_logger.py", line 46, in this_consume
    sensor_name = re_out.groupdict()['from']
AttributeError: 'NoneType' object has no attribute 'groupdict'

2016-11-25T13:16:36[CRITICAL] dripline.core.service(435) -> Service <slow_control_table> crashing with error message:
'NoneType' object has no attribute 'groupdict'
```
I think that's all the relevant part, but just in case this is the rest:
```
2016-11-25T13:16:36[ERROR   ] dripline.core.service(436) -> Traceback (most recent call last):
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/dripline-wp2.0.0_python3.3.3_0_gbbf8cec-py2.7.egg/dripline/core/service.py", line 433, in run
    self._connection.ioloop.start()
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 138, in start
    self.poller.start()
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 433, in start
    self.poll()
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 494, in poll
    self._handler(fileno, event, write_only=write_only)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 322, in _handle_events
    self._handle_read()
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/connection.py", line 1285, in _on_data_available
    self._process_frame(frame_value)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/connection.py", line 1365, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/connection.py", line 976, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/channel.py", line 792, in _handle_content_frame
    self._on_deliver(*response)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/pika/channel.py", line 886, in _on_deliver
    body)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/dripline-wp2.0.0_python3.3.3_0_gbbf8cec-py2.7.egg/dripline/core/service.py", line 326, in on_message
    msg_type_handlers[message.msgtype](unused_channel, basic_deliver, properties, body)
  File "/home/project8/python_environments/drag_v1.3.1_drip_wp2.0.0_python3.3.3_hard_v1.3.1/local/lib/python2.7/site-packages/dripline-wp2.0.0_python3.3.3_0_gbbf8cec-py2.7.egg/dripline/core/gogol.py", line 51, in on_alert_message
    self.this_consume(message_unpacked, method)
  File "build/bdist.linux-x86_64/egg/dragonfly/implementations/sensor_logger.py", line 46, in this_consume
    sensor_name = re_out.groupdict()['from']
AttributeError: 'NoneType' object has no attribute 'groupdict
```
My best guess is this is related to the new way of sending alerts to get them to slack?

**Comment by les67** [comment]
@wcpettus This is resolved in the branch bug/DatabaseIssue. Essentially, SensorLogger now has an explicit binding to sensor_value.# `kwargs.update({'exchange':'alerts','keys':['sensor_value.#']})` and will ignore messages therefore fixing this issue. I will submit a pull request once I've taken care of other bugs. See the thread in issue #30.

**Comment by les67** [comment]
I'd suggest either to close this issue since it's incorporated into issue #30 or you can assign it to me and I will close it once my branch is pulled.

**Comment by wcpettus** [comment]
Getting the other issue merged should be high priority, but if this is a duplicate, then closed.

**Comment by guiguem** [comment]
Not sure about the veracity of the "any" here.
We know the rsa makes the sensor logger. Did you try with another service? The error which is sent here is a request timed out which is not alert-related
The slack interface uses the alerts sent by the subcomponent of every dragonfly execution (service, command, execute) when a message is a critical log...
Therefore I am not sure about the title of the issue or the relation with the new slack.
Also I did not changed the way we sent alerts with the new slack handler.
