### ISSUE TITLE
RelaySpime set not working properly

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#91]
When setting one of the relays this morning, Noah received the following error:
```
(drag_v1.5.2_drip_wp2.1.1_python3.4.1_hard_v1.5.2)project8@claude:~$ dragonfly set esr_tickler_switch esr -b myrna.p8           
warning: slack is only ever critical, setting that
esr_tickler_switch->esr(ret:999): [glenlivet_relays]-> {u'values': [None]}
2017-02-06T10:27:41[Level 25] dragonfly.subcommands.dripline_agent(87) -> return message: global name 'exception' is not defined
```

Digging through the glenlivet relays error logfile, there are two instances of this issue.  Context extracted from stdout:
```
2017-02-06T10:27:41[DEBUG   ] dragonfly.implementations.spime_endpoints(153) -> value is esr; mapped value is: CLOSE
2017-02-06T10:27:41[DEBUG   ] dragonfly.implementations.ethernet_provider(154) -> sending: 'ROUTE:CLOSE (@5002)\r\n'
2017-02-06T10:27:41[DEBUG   ] dragonfly.implementations.ethernet_provider(196) -> 'ROUTE:CLOSE (@5002)\r\n34980A> '
2017-02-06T10:27:41[ERROR   ] dripline.core.endpoint(193) -> got an error: global name 'exception' is not defined
2017-02-06T10:27:41[ERROR   ] dripline.core.endpoint(194) -> traceback follows:
Traceback (most recent call last):
  File "/home/project8/python_environments/drag_v1.5.2_drip_wp2.1.1_python3.4.1_hard_v1.5.4_swarm_v1.3.5/local/lib/python2.7/site-packages/dripline-wp2.1.1_python3.4.1_0_g9a348a4-py2.7.egg/dripline/core/endpoint.py", line 181, in handle_request
    result = endpoint_method(*these_args, **these_kwargs)
  File "/home/project8/python_environments/drag_v1.5.2_drip_wp2.1.1_python3.4.1_hard_v1.5.4_swarm_v1.3.5/local/lib/python2.7/site-packages/dripline-wp2.1.1_python3.4.1_0_g9a348a4-py2.7.egg/dripline/core/endpoint.py", line 233, in _on_set
    result = self.on_set(value[0])
  File "/home/project8/python_environments/drag_v1.5.2_drip_wp2.1.1_python3.4.1_hard_v1.5.4_swarm_v1.3.5/local/lib/python2.7/site-packages/d
ripline-wp2.1.1_python3.4.1_0_g9a348a4-py2.7.egg/dripline/core/spime.py", line 23, in wrapper
    result = fun(*args, **kwargs)
  File "/home/project8/python_environments/drag_v1.5.2_drip_wp2.1.1_python3.4.1_hard_v1.5.4_swarm_v1.3.5/local/lib/python2.7/site-packages/d
ripline-wp2.1.1_python3.4.1_0_g9a348a4-py2.7.egg/dripline/core/endpoint.py", line 84, in wrapper
    fun(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/dragonfly/implementations/spime_endpoints.py", line 154, in on_set
    return self.provider.send([self._set_str.format(mapped_value)])
  File "build/bdist.linux-x86_64/egg/dragonfly/implementations/ethernet_provider.py", line 120, in send
    data = self._send_commands(commands)
  File "build/bdist.linux-x86_64/egg/dragonfly/implementations/ethernet_provider.py", line 167, in _send_commands
    raise exception.DriplineHardwareResponselessError("Bad ethernet query return: {}".format(data))
NameError: global name 'exception' is not defined

2017-02-06T10:27:41[DEBUG   ] dripline.core.endpoint(197) -> request method execution complete
```

This bug appears to have two parts:
- EthernetProvider line 167 has a typo ("exception" instead of "exceptions")
- RelaySpime is not returning a response, just an echo

**Comment by wcpettus** [comment]
fixed in hotfix v1.5.3, now tagged in master
