### ISSUE TITLE
empty broadcast.ping

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#95]
When there is no service running on a broker, we get the following:
```bash
dragonfly cmd broadcast.ping -b higgsino.physics.ucsb.edu -vvv
warning: slack is only ever critical, setting that
2017-02-10T19:47:30[DEBUG   ] dragonfly(268) -> calling <dragonfly.subcommands.dripline_agent.Cmd object at 0x103a35310> with args:
{'timeout': 10, 'target': 'broadcast.ping', 'pretty_print': False, 'broker': 'higgsino.physics.ucsb.edu', 'tmux': None, 'values': [], 'func': <dragonfly.subcommands.dripline_agent.Cmd object at 0x103a35310>, 'lockout_key': None, 'config': None, 'verbose': 3}
2017-02-10T19:47:30[DEBUG   ] dragonfly.subcommands.dripline_agent(29) -> in agent, got args:
Namespace(broker='higgsino.physics.ucsb.edu', config=None, func=<dragonfly.subcommands.dripline_agent.Cmd object at 0x103a35310>, lockout_key=None, pretty_print=False, target='broadcast.ping', timeout=10, tmux=None, values=[], verbose=3)
2017-02-10T19:47:30[DEBUG   ] dragonfly.subcommands.dripline_agent(67) -> payload will be: {'values': []}
2017-02-10T19:47:30[DEBUG   ] dripline.core.service(519) -> request to send to <broadcast.ping> is: {
    "timestamp": "2017-02-11T03:47:30Z", 
    "sender_info": {
        "username": "guig098", 
        "exe": "/Users/guig098/Work/Project8/python_environments/dragonfly_test/bin/dragonfly", 
        "package": "dripline", 
        "service_name": "", 
        "hostname": "WE30935", 
        "version": "wp2.1.0", 
        "commit": "g0e42b5a"
    }, 
    "payload": {
        "values": []
    }, 
    "msgop": 9
}
2017-02-10T19:47:41[INFO    ] dragonfly.subcommands.dripline_agent(79) -> response:
[]
Traceback (most recent call last):
  File "/Users/guig098/Work/Project8/python_environments/dragonfly_test/bin/dragonfly", line 4, in <module>
    __import__('pkg_resources').run_script('dragonfly===v1.5.2-4-g70aadc5', 'dragonfly')
  File "/Users/guig098/Work/Project8/python_environments/dragonfly_test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/guig098/Work/Project8/python_environments/dragonfly_test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/guig098/Work/Project8/python_environments/dragonfly_test/lib/python2.7/site-packages/dragonfly-v1.5.2_4_g70aadc5-py2.7.egg/EGG-INFO/scripts/dragonfly", line 269, in <module>
    
  File "build/bdist.macosx-10.10-x86_64/egg/dragonfly/subcommands/dripline_agent.py", line 23, in __call__
  File "build/bdist.macosx-10.10-x86_64/egg/dragonfly/subcommands/dripline_agent.py", line 93, in _call
IndexError: list index out of range
```

This case should taken into account when pinging.

**Comment by wcpettus** [comment]
Fixed in v1.9.4
